// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetApps() {
  return window['go']['main']['App']['GetApps']();
}

export function RefreshCatalog() {
  return window['go']['main']['App']['RefreshCatalog']();
}

export function ToggleAutoUpdate(arg1, arg2) {
  return window['go']['main']['App']['ToggleAutoUpdate'](arg1, arg2);
}

export function ToggleInstall(arg1, arg2) {
  return window['go']['main']['App']['ToggleInstall'](arg1, arg2);
}
